# Generated by Django 4.1.3 on 2022-11-27 20:40
from typing import List

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=django.utils.timezone.now)),
                ("class_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Attendence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "PRESENT"),
                            ("ABSENT", "ABSENT"),
                            ("LATE", "LATE"),
                            ("SICK", "SICK"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classrooms.classroom",
                    ),
                ),
            ],
        ),
    ]
