version: "3"

services:
  school_db:
    image: postgres:14.3
    # You can all queries executed on the database by uncomment this
#    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - school_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - school_net

  base:
    image: school_base.2022.4_dr1
    build:
      context: backend/
      dockerfile: Dockerfile

  classroom:
    build:
      context: backend/classroom
      dockerfile: Dockerfile
    image: infnet/classroom:local
    container_name: classroom
    command: python manage.py runserver 0.0.0.0:8081
    env_file:
      - .env.default
    volumes:
      - ./backend/:/app/
    ports:
      - "8081:8081"
    networks:
      - school_net
    depends_on:
      - school_db
      - classroom_migrator

  classroom_migrator:
    build:
      context: backend/classroom
      dockerfile: Dockerfile
    image: infnet/classroom-migrator:local
    container_name: classroom_migrator
    command: python manage.py migrate
    env_file:
      - .env.default
    volumes:
      - ./backend/:/app/
    networks:
      - school_net
    depends_on:
      - school_db

volumes:
  school_db_data:

networks:
  school_net:
    driver: bridge
